[archive]
build_output_dir = 'Built'
archive_location = '\\us-aus-hilbuild\builds\niveristandadd-ons\custom devices\control_addon'

[projects.cd]
path = 'Source\Control Addon.lvproj'

[projects.api]
path = 'Source\Control Addon SysDef API.lvproj'

[[build.steps]]
name = 'Configuration Library'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Configuration Release'

[[build.steps]]
name = 'Engine Libraries'
type = 'lvBuildSpecAllTargets'
project = '{cd}'
build_spec = 'Engine Release'

[[build.steps]]
name = 'Workspace Object'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Workspace Object'

[[build.steps]]
name = 'Workspace Tool'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Workspace Tool'

[[build.steps]]
name = 'Workspace Tool EXE'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Workspace Tool EXE'

[[build.steps]]
name = 'SysDef API'
type = 'lvBuildSpec'
project = '{api}'
target = 'My Computer'
build_spec = 'System Definition API'

[package]
type = 'nipkg'
name = 'ni-control-addon-{veristand_version}'
dev_xml_path = 'Source\Addon\Custom Device Control Addon.xml'
install_destination = 'documents\National Instruments\NI VeriStand {veristand_version}'

[[release.steps]]
name = 'Master Release'
type = 'githubRelease'
2019_release_branches = ["master",]